title:               The Astral Café
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: false

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-toc
  
sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/about.md"
    values:
      layout: "default"
  - scope:
      path: "_notes/blog/**/*.md"
    values:
      layout: "note"
      toc: true
  - scope:
      path: "_notes/docs/**/*.md"
    values:
      layout: "note"
      toc: true

    
# TOC Settings
toc:
 min_level: 3
 max_level: 5
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
